services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - 18888:18888 
      - 4317:18889